In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot

In [2]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples=1000,n_features=5,n_classes=2,random_state=42)

In [3]:
X

array([[-0.43964281,  0.54254734, -0.82241993,  0.40136622, -0.85484   ],
       [ 2.82223116, -2.48085944, -1.14769139, -2.10113103,  3.04027792],
       [ 1.61838572, -1.36947785, -2.08411294, -1.17965857,  1.61360231],
       ...,
       [ 1.56038977, -0.22904063, -0.2344078 , -0.61957623, -1.10985576],
       [ 0.88692467, -0.22294581, -1.3088204 , -0.39617745, -0.40427827],
       [-2.74710392,  1.85043021, -0.19382614,  1.77741855, -1.58083381]])

In [4]:
y

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X,y, test_size=0.25,random_state=41)

In [6]:
X_train.shape,X_test.shape

((750, 5), (250, 5))

In [7]:
y_train.shape, y_test.shape

((750,), (250,))

In [8]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()

In [9]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [11]:
knn.score(X_train,y_train)

0.9133333333333333

In [12]:
y_pred = knn.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [16]:
accuracy_score(y_test,y_pred)

0.884

In [17]:
confusion_matrix(y_test,y_pred)

array([[124,   9],
       [ 20,  97]], dtype=int64)

In [18]:
params={
    "n_neighbors":[5,10,20,30,50,60,80,100,110],
    "algorithm":["auto", "ball_tree", "kd_tree", "brute"],
    "leaf_size":[10,20,30,40,50,70,90,100,110],
    "p":[1,2],
}

In [19]:
def objective(trial, data=X, target=y):
    X_train,X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=34)
    params={
        "n_neighbors":[5,10,20,30,50,60,80,100,110],
        "algorithm":["auto", "ball_tree", "kd_tree", "brute"],
        "leaf_size":[10,20,30,40,50,70,90,100,110],
        "p":[1,2]
    }
    model =xgb.XGBregressor(**params)
    model.fit(X_train,y_train)
    y_pred = xgb_reg_model.predict(X_test)
    score = accuracy_score(y_test,y_pred)
    return score

In [20]:
import optuna

In [25]:
knn2=KNeighborsClassifier(algorithm="kd_tree")
knn2.fit(X_train,y_train)
knn2_pred = knn2.predict(X_test)
accuracy_score(y_test,knn2_pred)

0.884

In [27]:
knn3=KNeighborsClassifier(algorithm="ball_tree")
knn3.fit(X_train,y_train)
knn3_pred = knn3.predict(X_test)
accuracy_score(y_test,knn3_pred)

0.884

In [21]:

study = optuna.create_study()
study.optimize(objective(),n_trial=10)
study.best_trial.params

[I 2023-10-23 09:51:37,938] A new study created in memory with name: no-name-2a1c5b51-96f0-4314-8658-767f953d8db3


TypeError: objective() missing 1 required positional argument: 'trial'